# .streamlit/confiig.toml
[theme]
base = "dark"

# Primary accent color.
primaryColor = "#008000"

# Background color of the app.
backgroundColor = "#008000"

# Background color used for most interactive widgets.
secondaryBackgroundColor ="#008000"

# Color used for almost all text.
textColor ="#000000"